# Generated by Django 3.1.2 on 2020-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
