# Generated by Django 3.1.2 on 2020-11-09 02:24

import datetime
from django.db import migrations, models
import reportingTool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_de_depistage', models.CharField(choices=[('', 'Choisissez'), ('Tuberculose', 'Tuberculose'), ('CPN2 et Plus + Acccouch + CPoN', 'CPN2 et Plus + Acccouch + CPoN'), ('IST', 'IST'), ('Hospitalisation', 'Hospitalisation'), ('Index testing', 'Index testing'), ('Urgence', 'Urgence'), ('Malnutrition', 'Malnutrition'), ('Autre CDIP', 'Autre CDIP')], max_length=30, null=True)),
                ('date_de_depistage', models.DateField(default=datetime.date.today, null=True)),
                ('code_patient', models.CharField(max_length=25, validators=[reportingTool.models.Patient.code_patient_validate])),
                ('genre', models.CharField(choices=[('', 'Choisissez'), ('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True, validators=[reportingTool.models.Patient.age_validate])),
                ('conseiller', models.CharField(choices=[('', 'Choisissez'), ('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True)),
                ('depister', models.CharField(choices=[('', 'Choisissez'), ('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True)),
                ('resultat', models.CharField(choices=[('', 'Choisissez'), ('Positif', 'Positif'), ('Négatif', 'Négatif'), ('Indéterminer', 'Indéterminer'), ('Statut connu', 'Statut connu')], max_length=15, null=True)),
                ('resultat_recu', models.CharField(choices=[('', 'Choisissez'), ('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True)),
                ('beneficiant_CD4', models.CharField(choices=[('', 'Choisissez'), ('OUI', 'OUI'), ('NON', 'NON')], max_length=3, null=True)),
            ],
        ),
    ]
