# Generated by Django 3.1.2 on 2020-11-08 22:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviRdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_visite', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type de Visite')),
                ('date_rappel', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 8))], verbose_name='Date de Rappel')),
                ('methode_rappel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Méthode de rappel')),
                ('feedback_rappel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feedback rappel')),
                ('date_derniere_relance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 8))], verbose_name='Date de dernière relance')),
                ('methode_derniere_relance', models.CharField(blank=True, max_length=20, null=True, verbose_name='Méthode de dernière relance')),
                ('feedback_derniere_relance', models.CharField(blank=True, max_length=50, null=True, verbose_name='feedback de la dernière relance')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_rdv', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Suivi des RDV',
                'verbose_name_plural': 'Suivi des RDV',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activité', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSujetIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code du sujet contact')),
                ('nature_lien', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nature du lien avec le sujet index')),
                ('sexe', models.CharField(blank=True, max_length=5, null=True, verbose_name='Sexe du contact')),
                ('date_naissance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 8))], verbose_name='Date de naissance')),
                ('statut_identification', models.CharField(blank=True, max_length=20, null=True, verbose_name="Statut à l'identification")),
                ('date_depistage', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 8))], verbose_name='Date de dépistage')),
                ('resultat_depistage', models.CharField(blank=True, max_length=20, null=True, verbose_name='Résultat de dépistage')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_sujet_index', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Contact du sujet Index',
                'verbose_name_plural': 'Contacts du sujet Index',
            },
        ),
        migrations.CreateModel(
            name='RendezVousManque',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Rendez-Vous Manqués',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('relance.rendezvous',),
        ),
    ]
