# Generated by Django 3.1.2 on 2020-11-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'verbose_name': 'Rendez-Vous', 'verbose_name_plural': 'Rendez-Vous'},
        ),
    ]
