# Generated by Django 3.1.2 on 2020-11-09 17:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20201109_1756'),
        ('relance', '0002_auto_20201108_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviRdvARV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_visite', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type de Visite')),
                ('date_rappel', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de Rappel')),
                ('methode_rappel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Méthode de rappel')),
                ('feedback_rappel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feedback rappel')),
                ('date_derniere_relance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de dernière relance')),
                ('methode_derniere_relance', models.CharField(blank=True, max_length=20, null=True, verbose_name='Méthode de dernière relance')),
                ('feedback_derniere_relance', models.CharField(blank=True, max_length=50, null=True, verbose_name='feedback de la dernière relance')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_rdv_arv', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Suivi des RDV ARV',
                'verbose_name_plural': 'Suivi des RDV ARV',
            },
        ),
        migrations.CreateModel(
            name='SuiviRdvCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_visite', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type de Visite')),
                ('date_rappel', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de Rappel')),
                ('methode_rappel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Méthode de rappel')),
                ('feedback_rappel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feedback rappel')),
                ('date_derniere_relance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de dernière relance')),
                ('methode_derniere_relance', models.CharField(blank=True, max_length=20, null=True, verbose_name='Méthode de dernière relance')),
                ('feedback_derniere_relance', models.CharField(blank=True, max_length=50, null=True, verbose_name='feedback de la dernière relance')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_rdv_cv', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Suivi des RDV CV',
                'verbose_name_plural': 'Suivi des RDV CV',
            },
        ),
        migrations.AlterField(
            model_name='contactsujetindex',
            name='code_contact',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Code du sujet contact'),
        ),
        migrations.AlterField(
            model_name='contactsujetindex',
            name='date_depistage',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de dépistage'),
        ),
        migrations.AlterField(
            model_name='contactsujetindex',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='contactsujetindex',
            name='resultat_depistage',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Résultat de dépistage'),
        ),
        migrations.DeleteModel(
            name='SuiviRdv',
        ),
    ]
