# Generated by Django 3.1.2 on 2020-11-12 01:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20201112_0103'),
        ('relance', '0003_auto_20201109_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'verbose_name': 'Gestion des Rendez-Vous', 'verbose_name_plural': 'Gestion des Rendez-Vous'},
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_dernier_RDV_ARV',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de dernier RDV ARV'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_dernier_RDV_CV',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date dernier RDV CV'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_dernier_RDV_ETP',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='date de dernier RDV ETP'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nb_jour_ARV',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de Jours ARV'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nb_jour_CV',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de Jours avant la prochaine CV'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nb_jour_ETP',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Nombre de Jours ETP1'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='resultat_derniere_CV',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resultat derniere CV'),
        ),
        migrations.AlterField(
            model_name='contactsujetindex',
            name='date_depistage',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de dépistage'),
        ),
        migrations.AlterField(
            model_name='contactsujetindex',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='code_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='suivirdvarv',
            name='date_derniere_relance',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de dernière relance'),
        ),
        migrations.AlterField(
            model_name='suivirdvarv',
            name='date_rappel',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de Rappel'),
        ),
        migrations.AlterField(
            model_name='suivirdvcv',
            name='date_derniere_relance',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de dernière relance'),
        ),
        migrations.AlterField(
            model_name='suivirdvcv',
            name='date_rappel',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 12))], verbose_name='Date de Rappel'),
        ),
        migrations.CreateModel(
            name='ProchainRendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prochains_rdv', to='patients.patient')),
                ('rdv', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prochains_rdv', to='relance.rendezvous')),
            ],
            options={
                'verbose_name': 'Date Prévu Prochains Rendez-Vous',
                'verbose_name_plural': 'Dates Prévu Prochains Rendez-Vous',
            },
        ),
    ]
