# Generated by Django 3.1.2 on 2020-11-03 12:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import river.models.fields.state


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('river', '0002_auto_20201031_2349'),
        ('agents', '0002_auto_20201102_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=20, verbose_name='Code du dossier')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'permissions': [('can_manipulate_folders', 'Can manipulate folders')],
            },
        ),
        migrations.CreateModel(
            name='EmplacementMPTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='archivage.emplacementmptt')),
            ],
            options={
                'verbose_name': 'Emplacement de dossiers',
                'verbose_name_plural': 'Emplacements de dossiers',
            },
        ),
        migrations.CreateModel(
            name='FolderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=50, verbose_name='Libelle')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie de dossiers',
                'verbose_name_plural': 'Catégories de dossiers',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('sens', models.CharField(blank=True, max_length=3, verbose_name='Sens')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='agents.agent')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='archivage.dossier')),
                ('emplacement', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='archivage.emplacementmptt')),
            ],
            options={
                'verbose_name': 'Mouvement de dossier',
                'verbose_name_plural': 'Mouvements des dossiers',
                'ordering': ['dossier', '-creation_time'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='categorie_dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='archivage.foldercategory', verbose_name='Catégorie de dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='state',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.state'),
        ),
    ]
