# Generated by Django 3.1.2 on 2020-11-15 15:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_patient', models.CharField(max_length=20, unique=True, verbose_name='Code Patient')),
                ('presence_soins', models.CharField(blank=True, max_length=20, null=True, verbose_name='Présence dans les soins')),
                ('sexe', models.CharField(blank=True, max_length=15, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 15))], verbose_name='Date de Naissance')),
                ('date_enrolement', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 15))], verbose_name="Date d'enrolement")),
                ('Date_de_mise_sous_ARV', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 15))], verbose_name='Date de mise sous traitement ARV')),
                ('nom_conseiller', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom et Prénoms du conseiller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
