# Generated by Django 3.1.2 on 2020-11-09 17:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_dernier_RDV_ARV',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date de dernier RDV ARV'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_dernier_RDV_CV',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='Date dernier RDV CV'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_dernier_RDV_ETP',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 11, 9))], verbose_name='date de dernier RDV ETP'),
        ),
    ]
