# Generated by Django 3.1.2 on 2020-11-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20201112_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='statut_ARV',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_fin_traitement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Fin de Traitement'),
        ),
    ]
